export const medicineNames = [
  "TAB. PARACETAMOL 500MG",
  "TAB. IBUPROFEN 400MG",
  "CAP. AMOXICILLIN 500MG",
  "SYP. COUGH SYRUP",
  "OINT. NEOSPORIN",
  "CREAM CLOTRIMAZOLE",
  "TAB. CETIRIZINE 10MG",
  "TAB. PANTOPRAZOLE 40MG",
  "CAP. OMEPRAZOLE 20MG",
  "SYP. MULTIVITAMIN"
];
